---
- name: Install the docker apt package
  ansible.builtin.apt:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
    update_cache: true
    cache_valid_time: 3600
    
- name: Install the docker-compose apt package
  ansible.builtin.apt:
    name: "{{ docker_compose_package }}"
    state: "{{ docker_compose_package_state }}"
  when: install_docker_compose

- name: Add users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "{{ docker_group }}"
    append: true
  loop: "{{ docker_users }}"
  when:
    - docker_users is defined
    - docker_users | length > 0
